### ISSUE TITLE
mac 11.7.10不支持

### ISSUE THREAD

**Issue by zsf513** [MyMonsterCat/RapidOcr-Java#21]
Exception in thread "main" java.lang.UnsatisfiedLinkError: /private/var/folders/b5/ns76dt9d0j96tz0v5rzcg9vm0000gn/T/ocrJava/onnx/libRapidOcr.dylib: dlopen(/private/var/folders/b5/ns76dt9d0j96tz0v5rzcg9vm0000gn/T/ocrJava/onnx/libRapidOcr.dylib, 1): Symbol not found: __ZNSt3__113basic_filebufIcNS_11char_traitsIcEEEC1Ev
  Referenced from: /private/var/folders/b5/ns76dt9d0j96tz0v5rzcg9vm0000gn/T/ocrJava/onnx/libRapidOcr.dylib (which was built for Mac OS X 12.6)
  Expected in: /usr/lib/libc++.1.dylib

	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at io.github.mymonstercat.JarFileUtil.copyFileFromJar(JarFileUtil.java:68)
	at io.github.mymonstercat.OnnxMacX8664LibraryLoader.loadLibrary(OnnxMacX8664LibraryLoader.java:14)
	at io.github.mymonstercat.ocr.InferenceEngine.loadFileIfNeeded(InferenceEngine.java:78)
	at io.github.mymonstercat.ocr.InferenceEngine.runOcr(InferenceEngine.java:55)
	at io.github.mymonstercat.ocr.InferenceEngine.runOcr(InferenceEngine.java:50)

<img width="322" alt="image" src="https://github.com/MyMonsterCat/RapidOcr-Java/assets/4221354/5492c496-7735-4643-9f52-57b72e8f1ab9">

mac 11.7.10，intel处理器不支持。可否做到更低版本的os兼容？

**Comment by MyMonsterCat** [comment]
设备有限，没有InterCore的mac设备，所以没办法编译相应的动态库。这个可以参考自己编译一下[编译说明](https://github.com/RapidAI/RapidOcrOnnx/blob/main/BUILD.md)

**Comment by zsf513** [comment]
已编译好库文件。建议可以通过配置指定库文件的位置，如果未指定则使用jar包中默认的库。

**Comment by zsf513** [comment]
在macos 11.7.10下自行编译后执行测试脚本时报错:
<img width="1440" alt="image" src="https://github.com/MyMonsterCat/RapidOcr-Java/assets/4221354/d0d15c04-6b92-472c-948d-364d6a25f932">

**Comment by MyMonsterCat** [comment]
> 已编译好库文件。建议可以通过配置指定库文件的位置，如果未指定则使用jar包中默认的库。

感谢反馈，这个有时间会加一下。

**Comment by MyMonsterCat** [comment]
> 在macos 11.7.10下自行编译后执行测试脚本时报错: <img alt="image" width="1440" src="https://private-user-images.githubusercontent.com/4221354/292548561-d0d15c04-6b92-472c-948d-364d6a25f932.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyOTI0MTgsIm5iZiI6MTcwMzI5MjExOCwicGF0aCI6Ii80MjIxMzU0LzI5MjU0ODU2MS1kMGQxNWMwNC02YjkyLTQ3MmMtOTQ4ZC0zNjRkNmEyNWY5MzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjNUMDA0MTU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDJkNWQ3YzRiMzM4OTYwYWM0YWYwOTA5YTVmZjQ3MGE5OTc0Y2JiMTE5NjNmZGIyMTgzZTE3NjE4MjMyY2RiOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jW_8Jfbsk9yaKExZ1XoBV3ED9As62eDBn8oqSn6TLY4">

应该是兼容性问题，一般先使用otool -L libRapidOcr.dylib检查下依赖项。C++和编译这一块不是太懂，我按照它提供的编译教程好几种系统都没啥问题，如果还有问题可以在那个项目下提个issue。

**Comment by zsf513** [comment]
希望提供下mac编译通过的opencv、onnxruntime版本

**Comment by MyMonsterCat** [comment]
> 希望提供下mac编译通过的opencv、onnxruntime版本

https://github.com/RapidAI/RapidOcrOnnx/releases/download/1.2.2/Project_RapidOcrOnnx-1.2.2.7z
