### ISSUE TITLE
有一个打包问题，咨询一下

### ISSUE THREAD

**Issue by lycfr** [MyMonsterCat/RapidOcr-Java#47]
`代码`
```
public static void main(String[] args) {
        String image_file = "";
        if (args.length == 0) {
            URL url = OCR.class.getClassLoader().getResource("test4.png");
            if (url != null) {
                image_file = url.getFile();
            } else {
                System.out.println("资源文件test4.png未找到");
                return;
            }
        } else {
            image_file = args[0];
        }
        long startTime = System.currentTimeMillis();
        InferenceEngine engine = InferenceEngine.getInstance(Model.ONNX_PPOCR_V4);
        OcrResult ocrResult = engine.runOcr(image_file);
        List<TextBlock> textBlocks = ocrResult.getTextBlocks();
        for (TextBlock block : textBlocks) {
            System.out.println(block);
        }
        System.out.println("End Test:" + (System.currentTimeMillis() - startTime) + " ms");
    }
```
`pom.xml`
```
<dependencies>
        <!--  rapidocr这个必须要引入     -->
        <!--  可前往maven中央仓库https://central.sonatype.com/artifact/io.github.mymonstercat/rapidocr/versions，查看版本      -->
        <!-- core -->
        <dependency>
            <groupId>io.github.mymonstercat</groupId>
            <artifactId>rapidocr</artifactId>
            <version>${ocr.common.version}</version>
        </dependency>
        <dependency>
            <groupId>io.github.mymonstercat</groupId>
            <artifactId>rapidocr-common</artifactId>
            <version>${ocr.common.version}</version>
        </dependency>

        <!--  一般只需要引入一个，CPU端建议使用onnx，移动端建议使用ncnn     -->
        <!--  可前往maven中央仓库https://central.sonatype.com/artifact/io.github.mymonstercat/rapidocr-onnx-platform/versions，查看版本      -->
        <dependency>
            <groupId>io.github.mymonstercat</groupId>
            <artifactId>rapidocr-onnx-models</artifactId>
            <version>${model.version.122}</version>
        </dependency>
        <dependency>
            <groupId>io.github.mymonstercat</groupId>
            <artifactId>rapidocr-onnx-macosx-arm64</artifactId>
            <version>${model.version.122}</version>
        </dependency>
        <dependency>
            <groupId>io.github.mymonstercat</groupId>
            <artifactId>rapidocr-onnx-macosx-x86_64</artifactId>
            <version>${model.version.122}</version>
        </dependency>
        <dependency>
            <groupId>io.github.mymonstercat</groupId>
            <artifactId>rapidocr-onnx-linux-x86_64</artifactId>
            <version>${model.version.122}</version>
        </dependency>
        <dependency>
            <groupId>io.github.mymonstercat</groupId>
            <artifactId>rapidocr-onnx-windows-x86_64</artifactId>
            <version>${model.version.122}</version>
        </dependency>
        <dependency>
            <groupId>io.github.mymonstercat</groupId>
            <artifactId>rapidocr-onnx-windows-x86</artifactId>
            <version>${model.version.122}</version>
        </dependency>
<!--        <dependency>-->
<!--            <groupId>io.github.mymonstercat</groupId>-->
<!--            <artifactId>rapidocr-onnx-linux-arm64</artifactId>-->
<!--            <version>${model.version.122}</version>-->
<!--        </dependency>-->

        <!-- other -->
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>2.0.3</version>
        </dependency>

    </dependencies>
```
我现在在Mac OS Intel芯片上运行时，报错了：
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: /private/var/folders/f_/mp2mfwk540dby1r_r5ny1jc80000gn/T/ocrJava/onnx/libRapidOcr.dylib: dlopen(/private/var/folders/f_/mp2mfwk540dby1r_r5ny1jc80000gn/T/ocrJava/onnx/libRapidOcr.dylib, 0x0001): tried: '/private/var/folders/f_/mp2mfwk540dby1r_r5ny1jc80000gn/T/ocrJava/onnx/libRapidOcr.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/f_/mp2mfwk540dby1r_r5ny1jc80000gn/T/ocrJava/onnx/libRapidOcr.dylib' (no such file), '/private/var/folders/f_/mp2mfwk540dby1r_r5ny1jc80000gn/T/ocrJava/onnx/libRapidOcr.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64'))
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817)
	at java.lang.Runtime.load0(Runtime.java:810)
	at java.lang.System.load(System.java:1086)
	at io.github.mymonstercat.JarFileUtil.copyFileFromJar(JarFileUtil.java:68)
	at io.github.mymonstercat.OnnxMacX8664LibraryLoader.loadLibrary(OnnxMacX8664LibraryLoader.java:14)
	at io.github.mymonstercat.ocr.InferenceEngine.loadFileIfNeeded(InferenceEngine.java:78)
	at io.github.mymonstercat.ocr.InferenceEngine.runOcr(InferenceEngine.java:55)
	at io.github.mymonstercat.ocr.InferenceEngine.runOcr(InferenceEngine.java:50)
	at com.lyyd.ocr.OCR.main(OCR.java:28)
```
看这个报错的是动态库加载找到了M芯片，我要如何在代码中去加载我maven目录下的对应平台的动态库呢？我在api上面没找到接口

**Comment by lycfr** [comment]
另外一个问题
```
<dependency>
            <groupId>io.github.mymonstercat</groupId>
            <artifactId>rapidocr-onnx-linux-arm64</artifactId>
            <version>${model.version.122}</version>
        </dependency>
```
这个jar拉取不下来，是版本有问题？
```
Could not find artifact io.github.mymonstercat:rapidocr-onnx-linux-arm64:pom:1.2.2 in central (https://repo.maven.apache.org/maven2)

```

**Comment by MyMonsterCat** [comment]
第一个问题：Inerl芯片的可能有些问题，我在这里下载编译好的dylib[https://github.com/RapidAI/RapidOcrOnnx/releases](onnx)。你可以拉取RapidOcr-Java，然后替换macosx-x86_64包内相应的dylib，重新打包到本地，使用本地的jar试一下。

**Comment by MyMonsterCat** [comment]
> 另外一个问题
> 
> ```
> <dependency>
>             <groupId>io.github.mymonstercat</groupId>
>             <artifactId>rapidocr-onnx-linux-arm64</artifactId>
>             <version>${model.version.122}</version>
>         </dependency>
> ```
> 
> 这个jar拉取不下来，是版本有问题？
> 
> ```
> Could not find artifact io.github.mymonstercat:rapidocr-onnx-linux-arm64:pom:1.2.2 in central (https://repo.maven.apache.org/maven2)
> ```

onnx-linux-arm64是前两天新上传的，还没有打包到中央仓库，同样拉取项目打包到本地，使用本地jar包。

**Comment by lycfr** [comment]
<img width="789" alt="image" src="https://github.com/MyMonsterCat/RapidOcr-Java/assets/29672247/56b97586-619d-40e5-a6ab-74d208303914">
[RapidOcrOnnx](https://github.com/RapidAI/RapidOcrOnnx/releases)
这几个后缀代表啥意思？不同平台怎么区分

**Comment by MyMonsterCat** [comment]
> <img alt="image" width="789" src="https://private-user-images.githubusercontent.com/29672247/328744114-56b97586-619d-40e5-a6ab-74d208303914.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNTA4ODQsIm5iZiI6MTcxNTE1MDU4NCwicGF0aCI6Ii8yOTY3MjI0Ny8zMjg3NDQxMTQtNTZiOTc1ODYtNjE5ZC00MGU1LWE2YWItNzRkMjA4MzAzOTE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDA2NDMwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5YjM0NThmNjY1NDFiZGMyYjU5Y2MxNzRjZjBiMTA1NWY0ZjQxY2I4ODZkOTM3NTA1MzNiYjExZjAzNTNiNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P0YcLp2FEtPyBs7cb4iu5M2n6RKVckwCXVXQrpECNdE">
> [RapidOcrOnnx](https://github.com/RapidAI/RapidOcrOnnx/releases) 这几个后缀代表啥意思？不同平台怎么区分

jni的
