### ISSUE TITLE
多线程识别时，会有空指针的情况出现

### ISSUE THREAD

**Issue by mbh1210554992** [MyMonsterCat/RapidOcr-Java#66]
<img width="1273" alt="image" src="https://github.com/user-attachments/assets/902aaa80-0aca-4fdd-9579-a6b1531ad99c">
运行上方代码，启动5个线程识别图片，每次都只有一个线程成功了，其他线程都报了空指针：

java.lang.NullPointerException
	at io.github.mymonstercat.ocr.InferenceEngine.loadFileIfNeeded(InferenceEngine.java:84)
	at io.github.mymonstercat.ocr.InferenceEngine.runOcr(InferenceEngine.java:55)
	at io.github.mymonstercat.ocr.InferenceEngine.runOcr(InferenceEngine.java:50)
<img width="1428" alt="image" src="https://github.com/user-attachments/assets/8948d96c-5b6a-427e-a513-60b4809a7586">

**Comment by rongrong1000** [comment]
试了一下确实会这样, 但是你应该预热一下即先执行一次, 再开启线程可能会解决此问题
