### ISSUE TITLE
java.lang.UnsatisfiedLinkError: com.benjaminwan.ocrlibrary.OcrEngine.detectInput(Lcom/benjaminwan/ocrlibrary/OcrInput;IIFFFZZ)Lcom/benjaminwan/ocrlibrary/OcrResult;

### ISSUE THREAD

**Issue by litongjava** [MyMonsterCat/RapidOcr-Java#74]
测试代码
```
  @Test
  public void test02() {
    HardwareConfig onnxConfig = HardwareConfig.getOnnxConfig();
    InferenceEngine engine = InferenceEngine.getInstance(Model.ONNX_PPOCR_V4, onnxConfig);

    byte[] bytes = FileUtil.readBytes(new File("C:\\Users\\Administrator\\Desktop\\01.jpg"));
    // 4. 创建 OcrInput 对象并设置属性
    OcrInput input = new OcrInput(bytes);
    OcrResult ocrResult = engine.runOcr(input, ParamConfig.getDefaultConfig());
    System.out.println(ocrResult.getStrRes().trim());
  }
```
错误信息
```
java.lang.UnsatisfiedLinkError: com.benjaminwan.ocrlibrary.OcrEngine.detectInput(Lcom/benjaminwan/ocrlibrary/OcrInput;IIFFFZZ)Lcom/benjaminwan/ocrlibrary/OcrResult;
	at com.benjaminwan.ocrlibrary.OcrEngine.detectInput(Native Method)
	at io.github.mymonstercat.ocr.InferenceEngine.runOcr(InferenceEngine.java:84)
	at com.litongjava.RapidOcrTest.test02(RapidOcrTest.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```

**Comment by rongrong1000** [comment]
win好像不支持 二进制图片

**Comment by roostinghawk** [comment]
我们的错误类似，难道真的不支持 widnows server？
Handler dispatch failed; nested exception is java.lang.UnsatisfiedLinkError: 'void com.benjaminwan.ocrlibrary.OcrEngine.setGpuIndex(int)
